apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudformation-operator-system
resources:
- https://github.com/JagratiS/cloudformation-operator.git/config/operator
- https://github.com/JagratiS/cloudformation-operator.git/config/crd
